### ISSUE TITLE
Support for `expanduser`

### ISSUE THREAD

**Issue by mzpqnxow** [zobayer1/logging-extras#8]
Hello, thanks for your effort on this project. Would you be interested in a PR that adds support for implicitly applying `os.path.expanduser()` to values during loading? I've not used the pyyaml implicit resolver feature before but using my copy pasta skills, I came up with this small addition which seems to work:

```python

class YAMLConfig(object):
    ...
    _shellvar_tag_matcher = re.compile(r"^~(\w*?)/")

    def __init__(self, config_yaml: str, **kwargs: Any):
        ...
        yaml.add_implicit_resolver("!shellvar", self._shellvar_tag_matcher, None, yaml.SafeLoader)
        yaml.add_constructor("!shellvar", self._shellvar_constructor, yaml.SafeLoader)

    def _shellvar_constructor(self, _loader: Any, node: Any):
        return os.path.expanduser(node.value)
```

This complements the envvar support you already implemented by allowing stuff like:

```yaml
  filename: ~/
...
  filename: ~username/whatever
```

 I haven't yet read the documentation on `add_constructor` / `add_implicit_resolver` so I'm not sure if there will be a side-effect or complete breakage of the envvar logic. I would have to do more testing before submitting

Thanks again for this project, aside from being useful for my projects, it was a nice demonstration of the implicit resolvers in pyyaml. Unfortunately I already reinvented this functionality as post-processing functions by recursively traverse an entire `list` or `dict`, making the replacements after load. It did a bit more than expand environment variables (via Jinja2) but it still could have been done this way, and with a lot less code. Wish I had known about this feature then :/

**Comment by mzpqnxow** [comment]
Also, I have no idea why I named it `_shellvar...`, sorry about that ... I will change before I submit anything

**Comment by zobayer1** [comment]
Hi, I am very sorry that I have been away from the internet for about a month. I will take a look at it as soon as possible. Many many advanced thanks for the PR.
